name = "news"
version = "1.0.0"

description = "TODO"
licences = ["AGPL-3.0"]

target = "erlang"

repository = { type = "github", user = "facundoolano", repo = "news.olano.dev" }
links = [
  { title = "Web site", href = "https://news.olano.dev" },
  { title = "Source ciode", href = "https://github.com/facundoolano/news.olano.dev" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
erlsom = ">= 1.5.2 and < 2.0.0"
birl = ">= 1.8.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
